### ISSUE TITLE
trackImage is nil when using cocoapods + use_frameworks

### ISSUE THREAD

**Issue by Sega-Zero** [vadymmarkov/MARKRangeSlider#14]
When specifying `use_frameworks!` in Podfile, all the resources are located in a separate framework bundle, so `[UIImage imageNamed:]` returns nil. This can be fixed with 2 ways - fast and the right way =)
1. replace `imageNamed:` with `imageNamed:inBundle:compatibleWithTraitCollection:` (works only ios8+)
2. create a separate resource bundle with images and reference it in code

**Comment by lkang** [comment]
I also ran into this issue today. Any estimate on a fix?

**Comment by vadymmarkov** [comment]
@Sega-Zero @lkang Should be fixed https://github.com/vadymmarkov/MARKRangeSlider/pull/20

**Comment by lkang** [comment]
Cool!
