### ISSUE TITLE
Doesn't work with smaller than standard thumb images. 

### ISSUE THREAD

**Issue by SergeyBulyno** [vadymmarkov/MARKRangeSlider#16]
Hi, I use smaller thumb image than standard. But them doesn't work properly.
Change  CGSize leftThumbImageSize = self.leftThumbImageView.frame.size;
    CGSize rightThumbImageSize = self.rightThumbImageView.frame.size;
in layoutSubviews to     CGSize leftThumbImageSize = self.leftThumbImageView.image.size;
    CGSize rightThumbImageSize = self.rightThumbImageView.image.size;
looks like fix.

**Comment by vadymmarkov** [comment]
@SergeyBulyno Should be fixed https://github.com/vadymmarkov/MARKRangeSlider/pull/21
