### ISSUE TITLE
Left value always starts from 0

### ISSUE THREAD

**Issue by kunalgupta1593** [vadymmarkov/MARKRangeSlider#18]
I installed Mark Range Slider and in it I gave the slider.minimumValue = 15 and leftValue as 20. But when i started scrolling it showed the left value to be 0 which was quite surprising.
I noticed that for each and every minimum value the code returns the starting value from 0. I tried a lot to understand and fix the issue but it didn't work.
I have implemented this party and willing to continue this . Please fix this issue as soon as possible because I can not afford to be late regarding this issue.

**Comment by fraggjkee** [comment]
https://github.com/vadymmarkov/MARKRangeSlider/issues/5#issuecomment-85456558

**Comment by vadymmarkov** [comment]
Should be fixed https://github.com/vadymmarkov/MARKRangeSlider/pull/19
