### ISSUE TITLE
trackImage

### ISSUE THREAD

**Issue by mkoppanen** [vadymmarkov/MARKRangeSlider#2]
Hello,

how does one actually change the track or range image? 

It seems that the image set during setUpViewComponents and changing the "trackImage" property doesn't change the image currently being used in trackImageView.

**Comment by vadymmarkov** [comment]
Hi,

@mkoppanen That's actually was a bug. Thanks for contribution. It's fixed now.

**Comment by mkoppanen** [comment]
Thanks!
