### ISSUE TITLE
UITableViewCell subView MARKRangeSlider issue

### ISSUE THREAD

**Issue by SyedHyder1988** [vadymmarkov/MARKRangeSlider#35]
Hi whenever, we are dragging, the table view controller is popping up to previous view controller so how could we handle such scenario? I mean how to stop from popping back to previous view controller?

**Comment by SyedHyder1988** [comment]
Hi, I found the solution,

In `UITableViewController` or `UIViewController` which has `UITableView` has to disable `interactivePopGestureRecognizer` in `viewDidAppear` and in **same** Controller developer has to enable `interactivePopGestureRecognizer` in `viewWillDisAppear` . Hope it helps.

Please close the issue.

**Comment by vadymmarkov** [comment]
I'm glad you solved that 😉
