### ISSUE TITLE
Weird handle under the left handle

### ISSUE THREAD

**Issue by etayluz** [vadymmarkov/MARKRangeSlider#7]
Works great except for a strange thing (see below).
There's a second handle under the left most handle.
Not doing anything special - just copied and pasted code from github to init the slider.

<img width="304" alt="screen shot 2015-07-19 at 12 43 29 am" src="https://cloud.githubusercontent.com/assets/1825834/8764537/3d6756be-2daf-11e5-9aee-ab882eeb6245.png">

**Comment by etayluz** [comment]
I realize now that if you do this:
MARKRangeSlider *slider = [MARKRangeSlider new];
slider.frame = YOUR_FRAME

this error will occur. Must be something with the init method.

**Comment by pronebird** [comment]
init calls initWithFrame. I guess it's like a double initialization issue.
